### PR TITLE
(hdf5) Fixing phantom2hdf5 compiling issues

### PR DESCRIPTION
**Pull request by cpinte**
There seems to be somme issues when trying to compile phantom2hdf5. 
Some of them appear to linked to KROME. I fixed to the best of my knowledge, but I am not 100% sure that this all ok.

### CODE REVIEW

**Comment by danieljprice** [comment]
I can't merge this. The new autodoc stuff requires that the module name appears in the middle of the comments section

**Comment by danieljprice** [comment]
so we can't have ifdefs around the module name

**Comment by cpinte** [comment]
Ok, this seems to be required by phantom2hdf5 to compile though. 
I can work with the current fix on my fork, so this is not a priority.

**Comment by cpinte** [comment]
I take it back, phantom2hdf5 compiles but crashes with following error message:
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: H5G.c line 752 in H5Gclose(): not a group
    major: Invalid arguments to routine
    minor: Inappropriate type

 FATAL ERROR! write_fulldump_hdf5: could not write arrays

With this dump : https://www.dropbox.com/s/oe0kgse2r5wiq32/hydrostatic_18790?dl=0

**Comment by danieljprice** [comment]
> Ok, this seems to be required by phantom2hdf5 to compile though.
> I can work with the current fix on my fork, so this is not a priority.

the way this is done needs to be fixed, it is not nice to change the module name depending on a compile-time option. A procedure pointer would be a better way to do it.

**Comment by dmentipl** [comment]
Is it possible to merge this for now? Then I can raise an issue to fix the ifdefs (which I can do (in the future)).

**Comment by cpinte** [comment]
I have almost fixed everything, give me 1/2h

**Comment by cpinte** [comment]
Everything to work ok now with procedure pointers that will select the binary fortran or hdf5 versions of the routines.
The only remaining thing is that the routine check_arrays is defined twice in both the binary fortran and hdf5 code, while the 2 routines are slightly different.

**Comment by danieljprice** [comment]
I was wondering about the missing file :)

**Comment by danieljprice** [comment]
Just for reference, I'm intending to merge this, but there's an ongoing test failure on master I would like to fix before piling more problems on top of it...

**Comment by dmentipl** [comment]
I've added some more fixes that I think should be able to merge this pull request. But due to issue #42 I can't push them myself.

Here is a patch to the current state of the pull request that should fix the remaining issues and update the documentation to clarify the usage of phantom2hdf5. It also removes the Makefile variable `PHANTOM2HDF5`.

```patch
diff --git a/build/Makefile b/build/Makefile
index 2bc73e10..b3cb3bac 100644
--- a/build/Makefile
+++ b/build/Makefile
@@ -2200,9 +2200,6 @@ cleanphantom2mcfost:
 #----------------------------------------------------
 # these are the sources for the phantom2hdf5 utility
 #
-ifeq ($(PHANTOM2HDF5), yes)
-    FPPFLAGS += -DPHANTOM2HDF5
-endif
 checkhdf5flags:
    ifneq ($(HDF5), yes)
 	@echo "-----------------------------"
@@ -2210,12 +2207,6 @@ checkhdf5flags:
 	@echo "-----------------------------"
 	${MAKE} err
    endif
-   ifneq ($(PHANTOM2HDF5), yes)
-	@echo "-------------------------------------"
-	@echo "Need to compile with PHANTOM2HDF5=yes"
-	@echo "-------------------------------------"
-	${MAKE} err
-   endif
 
 .PHONY: phantom2hdf5
 phantom2hdf5: checksystem checkparams checkhdf5flags $(OBJDUMP) readwrite_dumps.o phantom2hdf5.o
diff --git a/docs/hdf5.rst b/docs/hdf5.rst
index 106da7d6..3f50a76f 100644
--- a/docs/hdf5.rst
+++ b/docs/hdf5.rst
@@ -151,13 +151,21 @@ Converting standard output files to HDF5 format with phantom2hdf5
 ``phantom2hdf5`` is a utility that can convert standard Phantom dump
 files to HDF5 format.
 
-To compile it, type
+You need to compile it with the same options as you compiled Phantom to produce
+the original Phantom dump. For example, if you have a dusty disc dump to convert
+that you originally compiled with
 
 ::
 
-   make phantom2hdf5 HDF5=yes PHANTOM2HDF5=yes
+   make SETUP=dustydisc MAXP=10000000
 
-Recall that you may need to set ``HDF5ROOT`` too.
+then you would compile ``phantom2hdf5`` as follows
+
+::
+
+   make SETUP=dustydisc MAXP=10000000 HDF5=yes HDF5ROOT=$HDF5_DIR phantom2hdf5
+
+Recall that you will need to set ``HDF5_DIR`` appropriately for your system.
 
 Now pass a file (or a list of files) to the converter
 
diff --git a/src/main/readwrite_dumps_hdf5.F90 b/src/main/readwrite_dumps_hdf5.F90
index e4848fd5..1c24e715 100644
--- a/src/main/readwrite_dumps_hdf5.F90
+++ b/src/main/readwrite_dumps_hdf5.F90
@@ -7,10 +7,7 @@
 module readwrite_dumps_hdf5
 !
 ! This module contains all routines related
-!  to the data format.
-!
-!  For Phantom, the format is identical to sphNG
-!  (although with fewer arrays dumped)
+!  to the HDF5 data format.
 !
 ! :References: None
 !
@@ -41,7 +38,7 @@ module readwrite_dumps_hdf5
   character(len=80), parameter, public :: &    ! module version
     modid="$Id$"
 
-  public :: read_dump_hdf5,read_smalldump_hdf5,write_smalldump_hdf5,write_fulldump_hdf5
+  public :: read_dump_hdf5,read_smalldump_hdf5,write_smalldump_hdf5,write_fulldump_hdf5,write_dump_hdf5
   logical, target, public    :: opened_full_dump_hdf5       ! for use in analysis files if user wishes to skip small dumps
   logical, target, public    :: dt_read_in_hdf5             ! to determine if dt has been read in so that ibin & ibinold can be set on restarts
   integer, parameter :: is_small_dump = 1978
@@ -119,7 +116,7 @@ end subroutine write_smalldump_hdf5
 !  Generic subroutine for writing a dumpfile
 !+
 !-------------------------------------------------------------------
-subroutine write_dump_hdf5(t,dumpfile,fulldump,ntotal)
+subroutine write_dump_hdf5(t,dumpfile,fulldump,ntotal,dtind)
  use dim,            only:maxp,maxvxyzu,gravity,maxalpha,mhd,mhd_nonideal,   &
                           use_dust,use_dustgrowth,phantom_version_major,     &
                           phantom_version_minor,phantom_version_micro,       &
@@ -139,10 +136,7 @@ subroutine write_dump_hdf5(t,dumpfile,fulldump,ntotal)
                           graindens,h2chemistry,lightcurve,ndivcurlB, &
                           ndivcurlv
 #ifdef IND_TIMESTEPS
- use part,           only:ibin
-#ifdef PHANTOM2HDF5
- use part,           only:dt_in
-#endif
+ use part,           only:ibin,dt_in
 #endif
  use part,           only:gamma_chem
  use mpiutils,       only:reduce_mpi,reduceall_mpi
@@ -159,13 +153,14 @@ subroutine write_dump_hdf5(t,dumpfile,fulldump,ntotal)
  character(len=*), intent(in) :: dumpfile
  logical,          intent(in) :: fulldump
  integer(kind=8),  intent(in), optional :: ntotal
+ real(kind=4),     intent(in), optional :: dtind(:)
 
  integer           :: i
  integer           :: ierr
  integer(kind=8)   :: nparttot,npartoftypetot(maxtypes)
  logical           :: use_gas,ind_timesteps,const_av,prdrag,isothermal
  real              :: ponrhoi,rhoi,spsoundi
- real, allocatable :: pressure(:),dtind(:),beta_pr(:)
+ real, allocatable :: pressure(:),dtin(:),beta_pr(:)
  character(len=100):: fileident
  character(len=10) :: datestring, timestring
  character(len=30) :: string
@@ -229,7 +224,7 @@ subroutine write_dump_hdf5(t,dumpfile,fulldump,ntotal)
  endif
 
  if (fulldump) then
-    allocate(pressure(npart),beta_pr(npart),dtind(npart))
+    allocate(pressure(npart),beta_pr(npart),dtin(npart))
 
     ! Compute pressure and beta_pr array
     if (.not.done_init_eos) call init_eos(ieos,ierr)
@@ -258,11 +253,11 @@ subroutine write_dump_hdf5(t,dumpfile,fulldump,ntotal)
 
     ! Compute dtind array
 #ifdef IND_TIMESTEPS
-#ifdef PHANTOM2HDF5
-    if (ind_timesteps) dtind = dt_in
-#else
-    if (ind_timesteps) dtind = dtmax/2**ibin(1:npart)
-#endif
+       if (present(dtind)) then
+          dtin = dtind
+       else
+          dtin = dtmax/2**ibin(1:npart)
+       endif
 #endif
  endif
 
@@ -410,7 +405,7 @@ subroutine write_dump_hdf5(t,dumpfile,fulldump,ntotal)
                            iphase,       & !
                            pressure,     & !
                            alphaind,     & !
-                           dtind,        & !
+                           dtin,         & !
                            poten,        & !
                            xyzmh_ptmass, & !
                            vxyz_ptmass,  & !
@@ -453,7 +448,7 @@ subroutine write_dump_hdf5(t,dumpfile,fulldump,ntotal)
  call close_hdf5file(hdf5_file_id,error)
  if (error/=0) call fatal('write_fulldump_hdf5','could not close file')
 
- if (fulldump) deallocate(pressure,beta_pr,dtind)
+ if (fulldump) deallocate(pressure,beta_pr,dtin)
 
 end subroutine write_dump_hdf5
 
diff --git a/src/utils/phantom2hdf5.f90 b/src/utils/phantom2hdf5.f90
index 9da06650..c4c101be 100644
--- a/src/utils/phantom2hdf5.f90
+++ b/src/utils/phantom2hdf5.f90
@@ -18,10 +18,10 @@ program phantom2hdf5
 !   readwrite_dumps_hdf5
 !
  use dim,                     only:tagline
- use part,                    only:hfact
+ use part,                    only:hfact,dt_in
  use io,                      only:set_io_unit_numbers,iprint,idisk1
  use readwrite_dumps_fortran, only:read_dump_fortran,read_smalldump_fortran,write_fulldump_fortran
- use readwrite_dumps_hdf5,    only:read_dump_hdf5, write_fulldump_hdf5,write_smalldump_hdf5
+ use readwrite_dumps_hdf5,    only:read_dump_hdf5,write_dump_hdf5
  use eos,                     only:extract_eos_from_hdr
  use externalforces,          only:extract_iextern_from_hdr
  implicit none
@@ -69,11 +69,7 @@ program phantom2hdf5
        cycle over_args
     endif
 
-    if (fulldump) then
-       call write_fulldump_hdf5(time,trim(dumpfile))
-    else
-       call write_smalldump_hdf5(time,trim(dumpfile))
-    endif
+    call write_dump_hdf5(time,trim(dumpfile),fulldump=fulldump,dtind=dt_in)
 
  enddo over_args
 

```

**Comment by dmentipl** [comment]
In addition, the HDF5 format is missing some features in the native format, e.g. GR and Krome arrays.

**Comment by dmentipl** [comment]
I think the HDF5 format is on par with the native format in the current state of this pull request.

It seems like the MPI test failure is not related to the changes in the pull request. Is it possible to merge this?

**Comment by cpinte** [comment]
I have fixed the conflict with is due to filename change. It would be great if you could merge this (despite the test testsuite pb). Thanks.

**Comment by danieljprice** [comment]
the changes on this are an improvement, so thanks for the efforts. I will merge to avoid the broken phantom2hdf5 but there are still a number of issues here:
1. there is currently lots of manual maintenance required to keep the formats in sync
2. the header quantities have to be manually written and read in hdf5 and the struct would have to change every time another quantity is added to the header
3. array quantity read/write is also duplicated, this needs to be defined in only one place in the source code
4. there are now at least 5 fortran source code files required to be compiled just to read and write a file

As mentioned, I think there is a much better way to fix (3), which is the ultimate problem here, as per #43

**Comment by danieljprice** [comment]
certainly phantom2hdf5 can be written in a way that does not depend on the rest of phantom at all

**Pull request merged**
