### PR TITLE
Adding adaptive particle refinement

### PR DESCRIPTION
**Pull request by becnealon**
Type of PR: 
new feature

Description:
Adding adaptive particle refinement as described in Nealon and Price submitted.

Testing:
Regular test suite runs, standalone apr test runs as well.

Did you run the bots? yes/no

Did you update relevant documentation in the docs directory? yes/no

### CODE REVIEW

**Comment by danieljprice** [comment]
@becnealon I fixed the merge conflicts here, so this branch now appears to be updated to master.

As there are quite a lot of changes and so you retain ownership over the relevant lines of code, please can you run the bots on this branch as per instructions below?

https://phantomsph.readthedocs.io/en/latest/developer-guide/bots.html

**Comment by danieljprice** [comment]
I'm also slightly confused why the merged changes appear like new commits... did history get rewritten here at some point?

**Comment by becnealon** [comment]
Um we both know I'm not clever enough to do that, so don't know but certainly wasn't deliberate.
________________________________

**Comment by danieljprice** [comment]
I think it's ok, if I git diff against master then it shows only your changes, so I think it's all good. Please can you run the bots though ?

**Comment by danieljprice** [comment]
superseded by #595

**Pull request closed without merging**
